
  spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/smzdm_db?serverTimezone=GMT
      username: root
      password: mysql4869
      driver-class-name: com.mysql.cj.jdbc.Driver
    velocity:
      suffix: .html
      expose-session-attributes: true
#      toolbox-config-location: toolbox.xml
      cache: false
      allow-session-override: true
      date-tool-attribute: date
  server:
    port: 80
  mybatis:
    mapper-locations: classpath:/mapper/*Mapper.xml