package com.cskaoyan.smzdm.mapper;

import com.cskaoyan.smzdm.domain.Conversation;
import com.cskaoyan.smzdm.domain.VO.ConversationVO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConversationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conversation
     *
     * @mbg.generated Sun Sep 16 19:50:57 CST 2018
     */
    int deleteByPrimaryKey(Integer conversationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conversation
     *
     * @mbg.generated Sun Sep 16 19:50:57 CST 2018
     */
    int insert(Conversation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conversation
     *
     * @mbg.generated Sun Sep 16 19:50:57 CST 2018
     */
    int insertSelective(Conversation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conversation
     *
     * @mbg.generated Sun Sep 16 19:50:57 CST 2018
     */
    Conversation selectByPrimaryKey(Integer conversationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conversation
     *
     * @mbg.generated Sun Sep 16 19:50:57 CST 2018
     */
    int updateByPrimaryKeySelective(Conversation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conversation
     *
     * @mbg.generated Sun Sep 16 19:50:57 CST 2018
     */
    int updateByPrimaryKey(Conversation record);

    Integer getConversationId(Conversation conversation);

    List<ConversationVO> selectAll();

}