package com.cskaoyan.smzdm.mapper;

import com.cskaoyan.smzdm.domain.News;
import com.cskaoyan.smzdm.domain.VO.NewsVO;

import java.util.List;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Thu Sep 13 15:11:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Thu Sep 13 15:11:54 CST 2018
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Thu Sep 13 15:11:54 CST 2018
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Thu Sep 13 15:11:54 CST 2018
     */
    NewsVO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Thu Sep 13 15:11:54 CST 2018
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbg.generated Thu Sep 13 15:11:54 CST 2018
     */
    int updateByPrimaryKey(News record);

    List<News> selectAll();

    News selectNewsByPrimaryKey(Integer id);
}